apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-cloudrun-service
  namespace: lifepilot-478904
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"   # Always keep 1 instance warm
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/lifepilot-478904/lifepilot-repo/lifepilot:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "prod"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
